### ISSUE TITLE
Exposing API - Multiprocessing error

### ISSUE THREAD

**Issue by MoamenAbdelwahed** [momegas/megabots#31]
I've created a `main.app` file as described in `README` file

```
from megabots import bot, create_api

app = create_api(bot("qna-over-docs"))
```

then I just run uvicorn to get this issue

```
Using model: gpt-3.5-turbo
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/moamen/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/moamen/.local/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/moamen/.local/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/home/moamen/.local/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/moamen/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/moamen/megabots/main.py", line 3, in <module>
    app = create_api(bot("qna-over-docs"))
    raise RuntimeError(
RuntimeError:
            Impossible to find a valid index.
            Either provide a valid path to a pickle file or a directory.

```

Environment:

Python: 3.10
Pip: 23.1
OS: WSL - Ubuntu

**Comment by momegas** [comment]
I see. So thge bot tries to find an index to answer questions from. So heres what you should do.

Create a folder called `index` and place some .txt or .pdf files in there. Then the bot will read this and be able to answer questions from these docs.

Maybe I should make the error better.
